let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Casual Shirt",
    price: 5,
    desc: "ao thun dep",
    img: "images/img-1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "polo shirt",
    price: 10,
    desc: "ao thun dep",
    img: "images/img-2.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "T Shirt",
    price: 15,
    desc: "ao thun dep",
    img: "images/img-3.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "T Shirt dep",
    price: 12,
    desc: "ao thun dep",
    img: "images/img-4.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Mens suit",
    price: 15,
    desc: "ao thun dep",
    img: "images/img-5.jpg",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Casual shoes",
    price: 11,
    desc: "ao thun dep",
    img: "images/img-6.jpg",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "suit",
    price: 20,
    desc: "ao thun dep",
    img: "images/img-7.webp",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "T shirt",
    price: 17,
    desc: "ao thun dep",
    img: "images/img-8.jpg",
  },
  {
    id: "cbvxbcvsceldk",
    name: "denim shirt",
    price: 21,
    desc: "ao thun dep",
    img: "images/img-9.jpg",
  },
  {
    id: "oiopijmjkhuihb",
    name: "victory",
    price: 9,
    desc: "ao thun dep",
    img: "images/img-10.jpg",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "basic shirt",
    price: 6,
    desc: "ao thun dep",
    img: "images/img-11.jpg",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "T shirt 2 mau",
    price: 10,
    desc: "ao thun dep",
    img: "images/img-12.jpg",
  },
];
